version: '3.8'
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bismabaig/node-app:$BRANCH_NAME-latest
    environment:
      SERVER_PORT: '9000'
    ports:
      - "${EXT_PORT}:9000"
